import {IKeyLabel} from './common';

enum sectionKeys {
  arts = 'arts',
  automobiles = 'automobiles',
  books = 'books',
  business = 'business',
  fashion = 'fashion',
  food = 'food',
  health = 'health',
  home = 'home',
  insider = 'insider',
  magazine = 'magazine',
  movies = 'movies',
  nyregion = 'nyregion',
  obituaries = 'obituaries',
  opinion = 'opinion',
  politics = 'politics',
  realestate = 'realestate',
  science = 'science',
  sports = 'sports',
  sundayreview = 'sundayreview',
  technology = 'technology',
  theater = 'theater',
  tmagazine = 't-magazine',
  travel = 'travel',
  upshot = 'upshot',
  us = 'us',
  world = 'world',
}

const sectionSelect: Array<IKeyLabel> = [
  {key: sectionKeys.world, label: 'World'},
  {key: sectionKeys.arts, label: 'Arts'},
  {key: sectionKeys.automobiles, label: 'Automobiles'},
  {key: sectionKeys.books, label: 'Books'},
  {key: sectionKeys.business, label: 'Business'},
  {key: sectionKeys.fashion, label: 'Fashion'},
  {key: sectionKeys.food, label: 'Food'},
  {key: sectionKeys.health, label: 'Health'},
  {key: sectionKeys.home, label: 'Home'},
  {key: sectionKeys.insider, label: 'Insider'},
  {key: sectionKeys.magazine, label: 'Magazine'},
  {key: sectionKeys.movies, label: 'Movies'},
  {key: sectionKeys.nyregion, label: 'NY Region'},
  {key: sectionKeys.obituaries, label: 'Obituaries'},
  {key: sectionKeys.opinion, label: 'Opinion'},
  {key: sectionKeys.politics, label: 'Politics'},
  {key: sectionKeys.realestate, label: 'Real Estate'},
  {key: sectionKeys.science, label: 'Science'},
  {key: sectionKeys.sports, label: 'Sports'},
  {key: sectionKeys.sundayreview, label: 'Sunday Review'},
  {key: sectionKeys.technology, label: 'Technology'},
  {key: sectionKeys.theater, label: 'Theater'},
  {key: sectionKeys.tmagazine, label: 'T-magazine'},
  {key: sectionKeys.travel, label: 'Travel'},
  {key: sectionKeys.upshot, label: 'Upshot'},
  {key: sectionKeys.us, label: 'US'},
];

export {sectionSelect, sectionKeys};
