const sections = [
  {key: 'arts', label: 'arts'},
  {key: 'automobiles', label: 'automobiles'},
  {key: 'books', label: 'books'},
  {key: 'business', label: 'business'},
  {key: 'fashion', label: 'fashion'},
  {key: 'food', label: 'food'},
  {key: 'health', label: 'health'},
  {key: 'home', label: 'home'},
  {key: 'insider', label: 'insider'},
  {key: 'magazine', label: 'magazine'},
  {key: 'movies', label: 'movies'},
  {key: 'nyregion', label: 'nyregion'},
  {key: 'obituaries', label: 'obituaries'},
  {key: 'opinion', label: 'opinion'},
  {key: 'politics', label: 'politics'},
  {key: 'realestate', label: 'realestate'},
  {key: 'science', label: 'science'},
  {key: 'sports', label: 'sports'},
  {key: 'sundayreview', label: 'sundayreview'},
  {key: 'technology', label: 'technology'},
  {key: 'theater', label: 'theater'},
  {key: 't-magazine', label: 't-magazine'},
  {key: 'travel', label: 'travel'},
  {key: 'upshot', label: 'upshot'},
  {key: 'us', label: 'us'},
  {key: 'world', label: 'world'},
];

export default sections;
