export const defaultTheme = {
  mode: 'light',
  PRIMARY_HEADER_COLOR: '#5A83FF',
  PRIMARY_HEADER_TEXT_COLOR: '#FFFFFF',
  PRIMARY_BACKGROUND_COLOR: '#7DBEE4',
  DEFAULT_BACKGROUND_COLOR: '#F0F1F2',
  DEFAULT_BORDER_COLOR: '#C3C4C9',
  SELECTED_COLOR: '#918AE4',
  PRIMARY_TEXT_COLOR: '#1D1F27',
  PRIMARY_BUTTON_COLOR: '#FFFFFF',
  PRIMARY_CARD_COLOR: '#FFFFFF',
};

export type ThemeType = typeof defaultTheme;
